version: '3'

services:
  run:
    container_name: local-althingi-client-run
    build:
      args:
        - ENV=development
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./dist:/usr/local/apache2/htdocs/
    depends_on:
      - server
      - thumbor
    ports:
      - 8282:80
      - 8283:443

  server:
    image: dev-server

  test:
    container_name: local-althingi-client-test
    build:
      target: build-assets
      args:
        - ENV=development
      context: .
      dockerfile: Dockerfile
    command: npm run test


  thumbor:
    container_name: local-althingi-client-thumbor
    image: minimalcompact/thumbor:6.7.5
    restart: on-failure
    logging:
        driver: "json-file"
        options:
            max-size: "200k"
            max-file: "5"
