version: '3'

services:
  run:
    container_name: local-althingi-client-run
    build:
      args:
        - ENV=development
        - API_HOST=http://${DOCKER_GATEWAY_HOST:-host.docker.internal}:3000
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./dist:/usr/local/apache2/htdocs/
    depends_on:
    #   - server
      - thumbor
    ports:
      - 8282:80

  server:
    image: dev-server
    environment:
      STORE_URL: http://${DOCKER_GATEWAY_HOST:-host.docker.internal}:8083

  test:
    container_name: local-althingi-client-test
    build:
      target: build-assets
      args:
        - ENV=development
      context: .
      dockerfile: Dockerfile
    command: npm run test


  thumbor:
    container_name: local-althingi-client-thumbor
    image: minimalcompact/thumbor:7.0.0
    restart: on-failure
    logging:
        driver: "json-file"
        options:
            max-size: "200k"
            max-file: "5"
