version: '3'

services:
  run:
    container_name: althingi_client_run
    build:
      args:
        - ENV=development
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./dist:/usr/local/apache2/htdocs/
    ports:
      - 8082:80

  test:
    container_name: althingi_client_run_test
    build:
      target: build-assets
      args:
        - ENV=development
      context: .
      dockerfile: Dockerfile
    command: npm run test
